[project]
name = "supportcrew-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mahee0117", email = "maheshmsk2006@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "crew>=0.9.2",
    "crewai>=1.15.23",
    "openai>=2.54.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
supportcrew-ai = "supportcrew_ai:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
